# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: AuDHS Selbsthilfegruppe
description: Informationen zur Selbsthilfegruppe für Menschen mit ADHS und Autismus
baseurl: "/bay"
url: "https://eliottvincent.github.io"
og_image: /assets/img/profile-pic.jpg

header:
  pages:
    - name: Home
      slug: /
    - name: Kontakt
    - name: Impressum

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: kopfkirmes@proton.me
      
# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
